-- CreateEnum
CREATE TYPE "ROLE" AS ENUM ('USER', 'ADMIN');

-- AlterTable
ALTER TABLE "ADMIN" ADD COLUMN     "role" "ROLE" NOT NULL DEFAULT 'ADMIN';

-- AlterTable
ALTER TABLE "USER" ADD COLUMN     "role" "ROLE" NOT NULL DEFAULT 'USER';
